[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:med-chat]
command=/app/.venv/bin/uvicorn services.rag_chat_agent.api.main:app --host 0.0.0.0 --port 8100
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:med-autocomplete]
command=/app/.venv/bin/uvicorn services.autocomplete.api.main:app --host 0.0.0.0 --port 8101
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
